### ISSUE TITLE
50% of request have old version

### ISSUE THREAD

**Issue by tiloio** [denoland/deploy_feedback#113]
50% of the requests are hitting a server which has the version from before.

When I do a request two times in a row I will get a HTTP 502 and a successful answer:

0 | 2021-10-16 15:27:40 | [Error] | [europe-west4] | ReferenceError: encoedPath is not defined     at fileResponse (file:///src/webserver/server.js:12:7)     at handleRequest (file:///src/webserver/server.js:52:16)     at file:///src/webserver/server.js:56:21     at innerInvokeEventListeners (deno:ext/web/02_event.js:749:9)     at invokeEventListeners (deno:ext/web/02_event.js:788:5)     at dispatch (deno:ext/web/02_event.js:658:11)     at dispatchEvent (deno:ext/web/02_event.js:989:14)     at handleConn (deno:deploy/js/99_main.js:136:9)
-- | -- | -- | -- | --
1 | 2021-10-16 15:27:40 | [Info] | [europe-west4] | {   text: "Serving none cached response",   path: "/",   encodedPath: "./webserver/index.html" }

**Comment by tiloio** [comment]
My mistake :)
