### ISSUE TITLE
AWS SDK / DynamoDB Example doesn't work

### ISSUE THREAD

**Issue by orgsofthq** [denoland/deploy_feedback#116]
The documentation at https://deno.com/deploy/docs/tutorial-dynamodb/ gives an example of using the AWS SDK on Deploy imported via skypack.

When deployed, however, it doesn't work - giving a 502 Bad Gateway error and an error message is logged:

```
Error: [Package Error] "@aws-sdk/util-utf8-browser" no dependency version info found. (Imported by "@aws-crypto/sha256-browser").
    at https://cdn.skypack.dev/error/unknown:@aws-sdk/util-utf8-browser?from=@aws-crypto/sha256-browser:13:7
```

I've tried using esm/jspm/deno.land/skypack imports with various versions/configs. While it runs fine locally w/ Deno, the AWS SDK seems to always have an import related error when run on Deploy.

**Comment by gerabell** [comment]
I also tried it out today and failed - but I got a different error:


```
TypeError: that.write is not a function
    at fromString (https://cdn.skypack.dev/-/@aws-crypto/util@v2.0.1-Bugd2mNY7FkoHwX43Vzr/dist=es2019,mode=imports/optimized/@aws-crypto/util.js:292:21)
    at from (https://cdn.skypack.dev/-/@aws-crypto/util@v2.0.1-Bugd2mNY7FkoHwX43Vzr/dist=es2019,mode=imports/optimized/@aws-crypto/util.js:236:12)
    at Function.Buffer.from (https://cdn.skypack.dev/-/@aws-crypto/util@v2.0.1-Bugd2mNY7FkoHwX43Vzr/dist=es2019,mode=imports/optimized/@aws-crypto/util.js:241:10)
    at fromUtf8 (https://cdn.skypack.dev/-/@aws-crypto/util@v2.0.1-Bugd2mNY7FkoHwX43Vzr/dist=es2019,mode=imports/optimized/@aws-crypto/util.js:1614:19)
    at convertToBuffer2 (https://cdn.skypack.dev/-/@aws-crypto/util@v2.0.1-Bugd2mNY7FkoHwX43Vzr/dist=es2019,mode=imports/optimized/@aws-crypto/util.js:1620:14)
    at Sha2562.update (https://cdn.skypack.dev/-/@aws-crypto/sha256-browser@v2.0.0-TcXuiaBlIVhAwxA0suHY/dist=es2019,mode=imports/optimized/@aws-crypto/sha256-browser.js:173:47)
    at Sha2562.update (https://cdn.skypack.dev/-/@aws-crypto/sha256-browser@v2.0.0-TcXuiaBlIVhAwxA0suHY/dist=es2019,mode=imports/optimized/@aws-crypto/sha256-browser.js:215:17)
    at https://cdn.skypack.dev/-/@aws-sdk/signature-v4@v3.50.0-d9x1WBZGrPAEGniLde3y/dist=es2019,mode=imports/optimized/@aws-sdk/signature-v4.js:218:20
    at step (https://cdn.skypack.dev/-/tslib@v2.3.1-oagOtGnmjZ2E5Gt5m3zI/dist=es2019,mode=imports/optimized/tslib.js:221:23)
    at Object.next (https://cdn.skypack.dev/-/tslib@v2.3.1-oagOtGnmjZ2E5Gt5m3zI/dist=es2019,mode=imports/optimized/tslib.js:168:18)
```

**Comment by in64** [comment]
> tslib

use 
```
import { DynamoDBClient } from "https://esm.sh/@aws-sdk/client-dynamodb";
```
test ok
