### ISSUE TITLE
Error: Code generation from strings disallowed from this context

### ISSUE THREAD

**Issue by oscarotero** [denoland/deploy_feedback#125]
Hi.

I'm testing Deno deploy, using the template engine Nunjucks to generate the html code and get the following error:

```
Template render error: (/src/_includes/layout.njk)
  EvalError: Code generation from strings disallowed for this context
    at Module._prettifyError (https://deno.land/x/nunjucks@3.2.3/src/lib.js:32:11)
    at Template.render (https://deno.land/x/nunjucks@3.2.3/src/environment.js:468:23)
    at https://raw.githubusercontent.com/lumeland/lume/e1184bc5824ef1f044526de1c2e290027dc754ed/plugins/nunjucks.ts:31:38
    at new Promise (<anonymous>)
    at NunjucksEngine.render (https://raw.githubusercontent.com/lumeland/lume/e1184bc5824ef1f044526de1c2e290027dc754ed/plugins/nunjucks.ts:30:16)
    at LumeRenderer.#renderPage (https://raw.githubusercontent.com/lumeland/lume/e1184bc5824ef1f044526de1c2e290027dc754ed/core/renderer.ts:238:40)
    at async LumeRenderer.renderPageOnDemand (https://raw.githubusercontent.com/lumeland/lume/e1184bc5824ef1f044526de1c2e290027dc754ed/core/renderer.ts:134:24)
    at async LumeSite.renderPage (https://raw.githubusercontent.com/lumeland/lume/e1184bc5824ef1f044526de1c2e290027dc754ed/core/site.ts:209:9)
    at async serve (file:///src/on_demand.ts:31:18)
    at async Server.handler (file:///src/server.ts:7:28)
```

Looks like Deno Deploy does not allow `new Function()` (maybe for security reasons?) and it seems that this package is using it to compile the templates.

Is that correct? Is there any way to configure/change it?

Thanks!

**Comment by ci7lus** [comment]
I also encountered this error when I used [deno_dom](https://deno.land/x/deno_dom@v0.1.19-alpha/) on deploy.
The same goes for the part in problem.
https://deno.land/x/deno_dom@v0.1.19-alpha/src/dom/nwsapi.js#L766

**Comment by bnoordhuis** [comment]
Sorry for the belated reply, I missed your comment. Deploy indeed disables `eval()` and `new Function()` for security and auditability reasons. There is currently no way to opt in.

**Comment by oscarotero** [comment]
Ok, thanks. Do you have plans to enable it, at least optionally? I think there are a lot of libraries that depends on this feature.

**Comment by bnoordhuis** [comment]
No concrete plans but we're aware it's used in a number of libraries, so maybe in the future.

**Comment by TomokiMiyauci** [comment]
Any progress on this?

I report that mdx is not fully available due to [dynamic import constraint](https://github.com/denoland/deploy_feedback/issues/1)  and this constraint.

For Example:

```ts
import { compile, run } from "https://esm.sh/@mdx-js/mdx";
import * as runtime from "https://esm.sh/preact/jsx-runtime";
const mdx = `# hello`;

const vfile = await compile(mdx, {
  jsxImportSource: "preact",
});

const { default: MDXContent } = await import(
  `data:text/javascript,${vfile.value}`
); // Error

const vfile2 = await compile(mdx, {
  jsxImportSource: "preact",
  outputFormat: "function-body",
});

const { default: MDXContent2 } = new Function(String(vfile2.value))(runtime); // Error
```

**Comment by lucacasonato** [comment]
`new Function` and `eval` are now supported.
