### ISSUE TITLE
deno sqlite error logs Deno.openSync is not function

### ISSUE THREAD

**Issue by bobwatcherx** [denoland/deploy_feedback#136]
**my half code :**
```
import { Application,Router  } from "https://deno.land/x/oak/mod.ts";
import { DB } from "https://deno.land/x/sqlite/mod.ts";
import { oakCors } from "https://deno.land/x/cors/mod.ts";
const db = new DB("./datamain.sqlite"); > **error in here in my line logs**

```

**my logs**

### 
TypeError: Deno.openSync is not a function     at js_open (https://deno.land/x/sqlite@v3.1.3/build/vfs.js:27:24)     at denoOpen (wasm://wasm/0028f022:1:2960)     at sqlite3BtreeOpen (wasm://wasm/0028f022:1:148034)     at openDatabase (wasm://wasm/0028f022:1:144000)     at sqlite3_open_v2 (wasm://wasm/0028f022:1:149501)     at open (wasm://wasm/0028f022:1:3771)     at https://deno.land/x/sqlite@v3.1.3/src/db.ts:45:67     at setStr (https://deno.land/x/sqlite@v3.1.3/src/wasm.ts:13:24)     at new DB (https://deno.land/x/sqlite@v3.1.3/src/db.ts:45:24)     at **file:///src/main.ts:4:12**
--

**Comment by ry** [comment]
Deno.openSync is not supported in Deploy.

**Comment by footearth** [comment]
Is there a support plan?

**Comment by bartlomieju** [comment]
> Is there a support plan?

Currently there are no plans to support synchronous IO APIs

**Comment by EtienneK** [comment]
Any way around this? I am also using `deno-sqlite` and am also running into this error.

**Comment by ayame113** [comment]
> Any way around this?

I have created a library to address this issue: https://github.com/ayame113/mock-file
