### ISSUE TITLE
Dynamic functions / eval

### ISSUE THREAD

**Issue by BurntCaramel** [denoland/deploy_feedback#140]
I’ve tried deploying a project using https://github.com/DjDeveloperr/deno-canvas to Deno Deploy, and get the following error:

```
EvalError: Code generation from strings disallowed for this context
    at new Function (<anonymous>)
    at Qb (https://raw.githubusercontent.com/DjDeveloperr/deno-canvas/v1.3.0/src/lib.js:3977:17)
    at Rb (https://raw.githubusercontent.com/DjDeveloperr/deno-canvas/v1.3.0/src/lib.js:3985:15)
    at Module.<anonymous> (https://raw.githubusercontent.com/DjDeveloperr/deno-canvas/v1.3.0/src/lib.js:5090:30)
    at init (https://raw.githubusercontent.com/DjDeveloperr/deno-canvas/v1.3.0/src/canvaskit.ts:6:22)
    at init (https://raw.githubusercontent.com/DjDeveloperr/deno-canvas/v1.3.0/src/canvas.ts:6:20)
    at https://raw.githubusercontent.com/DjDeveloperr/deno-canvas/v1.3.0/mod.ts:2:22
```

The source is from creating a function with a custom body:
```js
function Qb(a, b) {
        a = Pb(a);
        return (new Function(
          "body",
          "return function " + a +
            '() {\n    "use strict";    return body.apply(this, arguments);\n};\n',
        ))(b);
      }
```

Is there some way to turn on this permission for my project, or is it a big security concern from your side?

See also: https://github.com/DjDeveloperr/deno-canvas/issues/21

**Comment by BurntCaramel** [comment]
This issue looks related, but it didn’t receive any replies: https://github.com/denoland/deploy_feedback/issues/125

**Comment by bnoordhuis** [comment]
`eval()` and `new Function()` are indeed disabled for security / auditability reasons.

Thanks for bringing that other issue to my attention, I'll reply there as well.

**Comment by lucacasonato** [comment]
`new Function` and `eval` are now supported.
