### ISSUE TITLE
connt connect to SMTP server (timeout 110)

### ISSUE THREAD

**Issue by mathe42** [denoland/deploy_feedback#194]
I maintain denomailer (https://github.com/EC-Nordbund/denomailer) a smtp client for deno and with https://github.com/EC-Nordbund/denomailer/issues/17 we saw that it did not run on deno deploy.

I tried to replecate it and got a much simpler example that creates an error:

```ts
const conn = await Deno.connect({hostname: "smtp.gmail.com", port: 25 })

console.log('DONE')
```

creates the log:

```
TimedOut: Connection timed out (os error 110)
     at async Object.connect (deno:ext/net/01_net.js:333:17)
     at async file:///src/mod.ts:1:14
```

The code works with no problems localy. 

> Note: I tried the same with the TLS port and `connectTls` but got the same problem.

> might be related to #132

**Comment by cknight** [comment]
See https://discord.com/channels/684898665143206084/684911491035430919/961964433524031498

> You can not connect to SMTP servers on ports 25, 465, or 587 due to abuse. we have an internal issue open to improve the error message

**Comment by mathe42** [comment]
Thanks! That's kinda bad but understandable...

**Comment by ajvanegasv** [comment]
> See https://discord.com/channels/684898665143206084/684911491035430919/961964433524031498
> 
> > You can not connect to SMTP servers on ports 25, 465, or 587 due to abuse. we have an internal issue open to improve the error message

Is that Discord channel private? I want to read more information about it, but it doesn't show anything on Discord. I want to implement email sending on a personal website I'm working on, but I see that the SMTP service is not working. I haven't tried it myself yet, but has this changed today, or is everything still the same?

**Comment by satyarohith** [comment]
> Is that Discord channel private?

No. You can join here: https://discord.gg/deno

> is everything still the same?

Yes, we still block SMTP ports to prevent abuse.
