### ISSUE TITLE
Requests hanging for a long time (17 minutes) before getting 502 bad gateway error

### ISSUE THREAD

**Issue by KyleJune** [denoland/deploy_feedback#212]
Here is an example of the network request details when this occurred. I left the page open and it hung for 17.57 minutes.

![image](https://user-images.githubusercontent.com/3241653/168492219-6e6c0a36-5ee2-4115-a449-f9b674ec6301.png)

After the page loaded, the favicon request took 561ms. My code adds a x-response-time header which shows my route only took 126ms. I'm guessing the 435ms difference is related to the previous isolate getting killed and a new one spinning up. The logs say the new isolate took 2.94 ms to start.

![image](https://user-images.githubusercontent.com/3241653/168492383-2a03210f-7dab-4178-9fa8-e8ff8c2cd010.png)

The issue can be reproduced by going to the following page and refreshing a few times. While it's hanging, if I open another browser and go to the url it works but if I refresh in the one where it's hanging it will continue to hang.

https://udibo-8fmyktbj332g.deno.dev/identity

Below is a copy of logs from the deployment. It includes logs for that favicon request.

```
Uncaught error UnexpectedEof: early eof at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)
2022-05-15 20:07:50
at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)
2022-05-15 20:07:50
[uncaught application error]: UnexpectedEof - early eof
2022-05-15 20:07:50
Uncaught error UnexpectedEof: early eof at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)
2022-05-15 20:07:50
at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)
2022-05-15 20:07:50
[uncaught application error]: UnexpectedEof - early eof
2022-05-15 20:07:50
Uncaught error UnexpectedEof: early eof at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)
2022-05-15 20:07:50
at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)
2022-05-15 20:07:50
[uncaught application error]: UnexpectedEof - early eof
2022-05-15 20:07:50
Uncaught error UnexpectedEof: early eof at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)
2022-05-15 20:07:50
at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)
2022-05-15 20:07:50
[uncaught application error]: UnexpectedEof - early eof
2022-05-15 20:07:50
GET https://udibo-8fmyktbj332g.deno.dev/favicon.ico
2022-05-15 19:49:52
Listening on: http://127.0.0.1:80
2022-05-15 19:49:52
isolate start time: 2.94 ms
2022-05-15 19:49:52
Uncaught error UnexpectedEof: early eof at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)
2022-05-15 19:49:50
at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)
2022-05-15 19:49:50
[uncaught application error]: UnexpectedEof - early eof
2022-05-15 19:49:50
Uncaught error UnexpectedEof: early eof at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)
2022-05-15 19:49:50
at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)
2022-05-15 19:49:50
[uncaught application error]: UnexpectedEof - early eof
2022-05-15 19:49:50
Uncaught error UnexpectedEof: early eof at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)
2022-05-15 19:49:50
at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)
2022-05-15 19:49:50
[uncaught application error]: UnexpectedEof - early eof
2022-05-15 19:49:50
Uncaught error UnexpectedEof: early eof at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)
2022-05-15 19:49:50
at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)
2022-05-15 19:49:50
[uncaught application error]: UnexpectedEof - early eof
2022-05-15 19:49:50
GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-G2BOC7Z2.js
2022-05-15 19:32:15
GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-3RTHM5IF.js
2022-05-15 19:32:15
GET https://udibo-8fmyktbj332g.deno.dev/images/profile.svg
2022-05-15 19:32:15
GET https://udibo-8fmyktbj332g.deno.dev/images/header.svg
2022-05-15 19:32:15
GET https://udibo-8fmyktbj332g.deno.dev/images/logo.svg
2022-05-15 19:32:15
GET https://udibo-8fmyktbj332g.deno.dev/client/main.js
2022-05-15 19:32:15
GET https://udibo-8fmyktbj332g.deno.dev/identity
2022-05-15 19:32:15
```

Another issue I found is that if I stay on that page for a minute, the logs will disappear and show the following error.

![image](https://user-images.githubusercontent.com/3241653/168492033-afa960fe-0273-4ed2-8390-cf71bf1d270e.png)

Below is a copy of the response from the logs api endpoint. It finished in 571ms with a 200 status.

https://dash.deno.com/_api/projects/1079291a-0fe7-4722-827b-a266d8622d9f/deployments/latest/logs
```
"ready"
{"time":"2022-05-15T19:25:23.205369855Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-3RTHM5IF.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:25:23.239494513Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-G2BOC7Z2.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:25:23.280186558Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-5Y4QLUFK.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:25:23.321576079Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-PVNIQNMU.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:25:23.354370188Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-XVNDDPJJ.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:25:26.769341232Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/main-Q4FMKPI7.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:25:26.803301891Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/favicon.ico\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:25:26.849842994Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-UPSDFJ4U.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:25:27.009553739Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/home-PUSATQQZ.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:37.535143324Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/identity\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:37.615564258Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/main.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:37.662314274Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/images/logo.svg\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:37.727159012Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/images/header.svg\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:37.782803151Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/images/profile.svg\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:37.825008186Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-3RTHM5IF.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:37.867359944Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-G2BOC7Z2.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:37.908853468Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-5Y4QLUFK.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:37.950885712Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-PVNIQNMU.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:38.006846002Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-XVNDDPJJ.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:38.592542875Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/main-Q4FMKPI7.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:38.633234315Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/favicon.ico\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:38.670733877Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-UPSDFJ4U.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:38.834084512Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/home-PUSATQQZ.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:41.837293028Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/robots.txt\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:41.838752135Z","message":"mainRouter error NotFoundError: file not found\n    at file:///src/routes/main.ts:55:23\n    at async dispatch (https://deno.land/x/oak@v10.5.1/middleware.ts:16:13)\n    at async dispatch (https://deno.land/x/oak@v10.5.1/middleware.ts:16:13)\n    at async file:///src/routes/main.ts:33:9\n    at async dispatch (https://deno.land/x/oak@v10.5.1/middleware.ts:16:13)\n    at async dispatch (https://deno.land/x/oak@v10.5.1/middleware.ts:16:13)\n    at async allowedMethods (https://deno.land/x/oak@v10.5.1/router.ts:332:13)\n    at async dispatch (https://deno.land/x/oak@v10.5.1/middleware.ts:16:13)\n    at async dispatch (https://deno.land/x/oak@v10.5.1/middleware.ts:16:13)\n    at async etag (https://deno.land/x/oak@v10.5.1/etag.ts:74:9)\nCaused by NotFoundError: No such file or directory\n    at createHttpError (https://deno.land/x/oak@v10.5.1/httpError.ts:105:12)\n    at send (https://deno.land/x/oak@v10.5.1/send.ts:129:19)\n    at async file:///src/routes/main.ts:50:13\n    at async dispatch (https://deno.land/x/oak@v10.5.1/middleware.ts:16:13)\n    at async dispatch (https://deno.land/x/oak@v10.5.1/middleware.ts:16:13)\n    at async file:///src/routes/main.ts:33:9\n    at async dispatch (https://deno.land/x/oak@v10.5.1/middleware.ts:16:13)\n    at async dispatch (https://deno.land/x/oak@v10.5.1/middleware.ts:16:13)\n    at async allowedMethods (https://deno.land/x/oak@v10.5.1/router.ts:332:13)\n    at async dispatch (https://deno.land/x/oak@v10.5.1/middleware.ts:16:13)\n","level":"error","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:47.475320410Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/identity\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:47.569020929Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/main.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:47.610456429Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/images/logo.svg\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:47.653789079Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/images/header.svg\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:47.691814302Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/images/profile.svg\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:47.737138493Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-3RTHM5IF.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:47.783522756Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-G2BOC7Z2.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:47.828370213Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-5Y4QLUFK.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:47.872255497Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-PVNIQNMU.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:47.909625891Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-XVNDDPJJ.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:48.760476855Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/main-Q4FMKPI7.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:48.832626534Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-UPSDFJ4U.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:48.913713090Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/home-PUSATQQZ.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:49.974087951Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/identity\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:50.174323562Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/main.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:50.213775267Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/images/logo.svg\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:50.254973575Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/images/header.svg\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:50.296762758Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/images/profile.svg\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:50.332647496Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-3RTHM5IF.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:50.369040891Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-G2BOC7Z2.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:50.403197178Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-5Y4QLUFK.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:50.436916471Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-PVNIQNMU.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:50.475044645Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-XVNDDPJJ.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:51.296480998Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/main-Q4FMKPI7.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:51.336320229Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/favicon.ico\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:51.387810042Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-UPSDFJ4U.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:26:51.541587601Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/home-PUSATQQZ.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:32:10.115210858Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/identity\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:32:10.368854467Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/main.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:32:10.480256784Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/images/logo.svg\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:32:10.516860725Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/images/header.svg\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:32:10.557787626Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/images/profile.svg\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:32:10.602751926Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-3RTHM5IF.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:32:10.635528163Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-G2BOC7Z2.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:32:10.675708673Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-5Y4QLUFK.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:32:10.713089489Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-PVNIQNMU.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:32:10.750220353Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-XVNDDPJJ.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:32:11.385673141Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/favicon.ico\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:32:11.542942986Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/main-Q4FMKPI7.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:32:11.794476491Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-UPSDFJ4U.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:32:11.934081243Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/home-PUSATQQZ.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:32:15.463498161Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/identity\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:32:15.587176417Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/main.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:32:15.719132745Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/images/logo.svg\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:32:15.756714706Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/images/header.svg\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:32:15.800641345Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/images/profile.svg\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:32:15.833074458Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-3RTHM5IF.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:32:15.878207879Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/client/chunk-G2BOC7Z2.js\n","level":"info","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:49:50.476873831Z","message":"[uncaught application error]: UnexpectedEof - early eof\n","level":"error","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:49:50.477144281Z","message":"\n    at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)\n","level":"error","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:49:50.477254986Z","message":"Uncaught error UnexpectedEof: early eof\n    at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)\n","level":"error","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:49:50.477608247Z","message":"[uncaught application error]: UnexpectedEof - early eof\n","level":"error","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:49:50.477687913Z","message":"\n    at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)\n","level":"error","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:49:50.477743073Z","message":"Uncaught error UnexpectedEof: early eof\n    at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)\n","level":"error","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:49:50.478018916Z","message":"[uncaught application error]: UnexpectedEof - early eof\n","level":"error","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:49:50.478115504Z","message":"\n    at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)\n","level":"error","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:49:50.478161658Z","message":"Uncaught error UnexpectedEof: early eof\n    at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)\n","level":"error","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:49:50.478410376Z","message":"[uncaught application error]: UnexpectedEof - early eof\n","level":"error","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:49:50.478480290Z","message":"\n    at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)\n","level":"error","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:49:50.478527123Z","message":"Uncaught error UnexpectedEof: early eof\n    at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)\n","level":"error","isolateId":"98e92016-c0b0-483f-8e91-11bea8ac6f72","region":"us-central1"}
{"time":"2022-05-15T19:49:52.003971834Z","message":"isolate start time: 2.94 ms","level":"debug","isolateId":"ddcbd742-5dfd-4b3d-84aa-3e12de3dc706","region":"us-central1"}
{"time":"2022-05-15T19:49:52.380922993Z","message":"Listening on: http://127.0.0.1:80\n","level":"info","isolateId":"ddcbd742-5dfd-4b3d-84aa-3e12de3dc706","region":"us-central1"}
{"time":"2022-05-15T19:49:52.397027126Z","message":"GET https://udibo-8fmyktbj332g.deno.dev/favicon.ico\n","level":"info","isolateId":"ddcbd742-5dfd-4b3d-84aa-3e12de3dc706","region":"us-central1"}
{"time":"2022-05-15T20:07:50.582291074Z","message":"[uncaught application error]: UnexpectedEof - early eof\n","level":"error","isolateId":"ddcbd742-5dfd-4b3d-84aa-3e12de3dc706","region":"us-central1"}
{"time":"2022-05-15T20:07:50.583601517Z","message":"\n    at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)\n","level":"error","isolateId":"ddcbd742-5dfd-4b3d-84aa-3e12de3dc706","region":"us-central1"}
{"time":"2022-05-15T20:07:50.584399910Z","message":"Uncaught error UnexpectedEof: early eof\n    at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)\n","level":"error","isolateId":"ddcbd742-5dfd-4b3d-84aa-3e12de3dc706","region":"us-central1"}
{"time":"2022-05-15T20:07:50.584785170Z","message":"[uncaught application error]: UnexpectedEof - early eof\n","level":"error","isolateId":"ddcbd742-5dfd-4b3d-84aa-3e12de3dc706","region":"us-central1"}
{"time":"2022-05-15T20:07:50.584954425Z","message":"\n    at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)\n","level":"error","isolateId":"ddcbd742-5dfd-4b3d-84aa-3e12de3dc706","region":"us-central1"}
{"time":"2022-05-15T20:07:50.585061952Z","message":"Uncaught error UnexpectedEof: early eof\n    at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)\n","level":"error","isolateId":"ddcbd742-5dfd-4b3d-84aa-3e12de3dc706","region":"us-central1"}
{"time":"2022-05-15T20:07:50.585385133Z","message":"[uncaught application error]: UnexpectedEof - early eof\n","level":"error","isolateId":"ddcbd742-5dfd-4b3d-84aa-3e12de3dc706","region":"us-central1"}
{"time":"2022-05-15T20:07:50.585849277Z","message":"\n    at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)\n","level":"error","isolateId":"ddcbd742-5dfd-4b3d-84aa-3e12de3dc706","region":"us-central1"}
{"time":"2022-05-15T20:07:50.585941373Z","message":"Uncaught error UnexpectedEof: early eof\n    at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)\n","level":"error","isolateId":"ddcbd742-5dfd-4b3d-84aa-3e12de3dc706","region":"us-central1"}
{"time":"2022-05-15T20:07:50.586273061Z","message":"[uncaught application error]: UnexpectedEof - early eof\n","level":"error","isolateId":"ddcbd742-5dfd-4b3d-84aa-3e12de3dc706","region":"us-central1"}
{"time":"2022-05-15T20:07:50.586433719Z","message":"\n    at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)\n","level":"error","isolateId":"ddcbd742-5dfd-4b3d-84aa-3e12de3dc706","region":"us-central1"}
{"time":"2022-05-15T20:07:50.586522365Z","message":"Uncaught error UnexpectedEof: early eof\n    at async accept (https://deno.land/x/oak@v10.5.1/http_server_native.ts:87:38)\n","level":"error","isolateId":"ddcbd742-5dfd-4b3d-84aa-3e12de3dc706","region":"us-central1"}
```

**Comment by KyleJune** [comment]
This might be an issue with oak since the logs are showing "unexpectedEof - early eof" from `oak/http_server_native.ts` at the same time the request finally finishes with a 502 error.

**Comment by lucacasonato** [comment]
@KyleJune What browser are you using?

**Comment by KyleJune** [comment]
Firefox developer edition. But I also had issue in chromium. My operating system is Ubuntu 20.04. I just reproduced it in chromium again right now.

**Comment by KyleJune** [comment]
I'm going to close this because I believe the change to oak will resolve it. I just haven't been able to test it yet because of issues with my esm.sh dependencies.
