### ISSUE TITLE
h is not defined

### ISSUE THREAD

**Issue by goodoldneon** [denoland/deploy_feedback#230]
I have a project that works locally, but when it's deployed the logs show `h is not defined`.

Here's the repo:

https://github.com/goodoldneon/deno-demo

In Deno Deploy's logs I'm seeing:

```
ReferenceError: h is not defined
    at Server.handler (file:///src/src/index.tsx:8:18)
    at Server.#respond (https://deno.land/std@0.140.0/http/server.ts:220:43)
    at Server.#serveHttp (https://deno.land/std@0.140.0/http/server.ts:254:26)
```

Does Deno Deploy only support SSR React via `nano_jsx` and the `/** @jsx h */` pragma?

**Comment by aslilac** [comment]
It supports any function named `h`, but you have to import it yourself (your JSX import source isn't getting inserted automatically)

We should probably fail to deploy if you have `"jsx": "react-jsx"` in your compiler options.

**Comment by sylvek** [comment]
Hi,

I have the same situation with a "standard" configuration 🤔 
It's working well locally but i have the same issue on log.

Here's the repo:
https://github.com/sylvek/hello-deno-deploy

**Comment by sylvek** [comment]
ho!.

it's working well if every tsx files are set with
`
/** @jsx jsx */`

**Comment by deckchairlabs** [comment]
> It supports any function named `h`, but you have to import it yourself (your JSX import source isn't getting inserted automatically)
> 
> We should probably fail to deploy if you have `"jsx": "react-jsx"` in your compiler options.

Can we get some feedback as to why this is the case, will Deploy support this in the future?

**Comment by goodoldneon** [comment]
Are there plans to obviate the need for the pragma? It isn’t a huge deal, but it’s a point of friction for our engineers. Migrating to Deno is an easier sell if engineers can continue writing React files the same way
