### ISSUE TITLE
Error `stack` line numbers do not match source line numbers

### ISSUE THREAD

**Issue by timfish** [denoland/deploy_feedback#262]
The following code:
https://dash.deno.com/playground/close-kingfisher-10

Results in:
```
Error: Error from line 3
    at file:///src/main.ts:2:15
```

Whereas it should be:
```
Error: Error from line 3
    at file:///src/main.ts:3:15
```

**Comment by jsejcksn** [comment]
I encountered the same issue: it appears that deploy is compiling the TypeScript during the deployment but at runtime (when the stack traces are generated) there seems to be a loss of source mapping info — I guess that either there are no source maps generated at compile time or that the runtime is just using them.
