### ISSUE TITLE
`Serving static assets` example code not working

### ISSUE THREAD

**Issue by AkifumiSato** [denoland/deploy_feedback#3]
This `mod.ts` is not working.
https://deno.com/deploy/docs/serve-static-assets

## local env
deno 1.8.2
deployctl 0.1.0

## error
```
Listening on http://0.0.0.0:8080
error: Uncaught (in promise) TypeError: scheme 'file' not supported
    return fetch(style);
^
    at handleError (deno:core/core.js:186:12)
    at jsonOpParseResult (deno:core/core.js:356:9)
    at opSync (deno:core/core.js:259:32)
    at Object.jsonOpSync (deno:core/core.js:372:12)
    at opFetch (deno:op_crates/fetch/26_fetch.js:887:17)
    at sendFetchReq (deno:op_crates/fetch/26_fetch.js:1257:44)
    at fetch (deno:op_crates/fetch/26_fetch.js:1379:31)
    at handleRequest (file:///Users/satouakifumi/work/git/personal/deno_deploy_blog/static_test.ts:16:1)
    at file:///Users/satouakifumi/work/git/personal/deno_deploy_blog/static_test.ts:37:1
    at innerInvokeEventListeners (deno:op_crates/web/02_event.js:750:27)
```

**Comment by satyarohith** [comment]
It will be fixed by https://github.com/denoland/deployctl/pull/23
