### ISSUE TITLE
Simple Deploy Errors

### ISSUE THREAD

**Issue by cfjello** [denoland/deploy_feedback#323]
In the deno deploy playground I tried this very simple app, trying to figure out how Deno Deploy resolves paths, since it seems different from my home environment (basically I am trying to figure out how to read data and html files from subdirectories and serve them using HTTP):

> import * as path from "https://deno.land/std@0.128.0/path/mod.ts"
> import { serve } from "https://deno.land/std@0.155.0/http/server.ts";
> 
> const __dirname = path.dirname(import.meta.url);
> 
> let files = []
> 
> console.debug(`__dirname: ${__dirname}`)
> for await (const dirEntry of Deno.readDir(path.normalize(__dirname))) {
>   files.push(JSON.stringify(dirEntry));
> }
> 
> serve((req: Request) => new Response(files.join());

Deploying this returns an error:

> NotFound: No such file or directory
>     at async Object.[Symbol.asyncIterator] (deno:deploy/js/02_fs.js:49:16)
>     at async file:///src/main.ts:4:18

This is probably not a bug and I do not know if this is a simpe case of the app lacking allow_read, so some advice would be appreciated.

**Comment by cfjello** [comment]
For some reason __dirname is not applicable in this environment, I must use Deno.cwd() instead.
