### ISSUE TITLE
Error: Dynamic import is not enabled in this context.

### ISSUE THREAD

**Issue by BoltDoggy** [denoland/deploy_feedback#38]
```
❗️ | TypeError: Dynamic import is not enabled in this context.
at async https://raw.githubusercontent.com/BoltDoggy/deno_server/aa835a760271d64d59858404822929f8ced727e9/mod.tsx:8:15     
at async https://raw.githubusercontent.com/BoltDoggy/deno_server/aa835a760271d64d59858404822929f8ced727e9/utils/JsxRouter.tsx:40:10
```

**Comment by bnoordhuis** [comment]
That's right, see #1. Closing as a duplicate but thanks for the feedback.
