### ISSUE TITLE
Deno deploy: `Deno.unrefTimer` is not a function

### ISSUE THREAD

**Issue by renhiyama** [denoland/deploy_feedback#381]
```js
TypeError: Deno.unrefTimer is not a function
    at Timeout.unref (https://deno.land/std@0.177.0/node/internal/timers.mjs:66:10)
    at M.setupSweepers (https://esm.sh/v119/@discordjs/rest@1.7.1/deno/rest.mjs:9:1468)
    at new RequestManager (https://esm.sh/v119/@discordjs/rest@1.7.1/deno/rest.mjs:9:864)
    at new REST (https://esm.sh/v119/@discordjs/rest@1.7.1/deno/rest.mjs:9:4544)
//My code scripts, its compiled script, not sure whether its of any use...?
```

My code seems to not run on deno deploy... Why is a deno runtime API not available on deno deploy?

**Comment by ry** [comment]
We're in the process of building native built-in Node modules support (and native npm support) into Deno Deploy with special enhancements for serverless. `Deno.unrefTimer` is a special binding that was added for node compatibility which will be removed from Deno runtime (because node built-ins are now native to Deno)

**Comment by renhiyama** [comment]
May I know why deno deploy isn't the same as deno runtime? Deno seems to have lot more features (APIs) than Deno deploy, yet deno deploy boasts about running deno based programs? Is there any architecture blog or something that tells whats the difference or how deno deploy is different from deno, and how its differently optimised from deno to work for deno deploy?

**Comment by vwkd** [comment]
https://deno.com/deploy/docs/runtime-api
