### ISSUE TITLE
[Bug]: `TypeError: ops.op_set_keepalive is not a function`

### ISSUE THREAD

**Issue by audionerd** [denoland/deploy_feedback#382]
### Problem description

My project has been running on Deno Deploy for the past 7 days untouched. It recently started throwing 500 errors, `ops.op_set_keepalive is not a function`. I’m using `postgresjs@3.3.4`, which is the latest version.

```js
TypeError: ops.op_set_keepalive is not a function
    at TcpConn.setKeepAlive (ext:deno_net/01_net.js:162:16)
    at Object.setKeepAlive (https://deno.land/x/postgresjs@v3.3.4/polyfills.js:37:61)
    at connected (https://deno.land/x/postgresjs@v3.3.4/src/connection.js:365:51)
    at https://deno.land/x/postgresjs@v3.3.4/polyfills.js:150:32
    at Array.forEach (<anonymous>)
    at call (https://deno.land/x/postgresjs@v3.3.4/polyfills.js:150:18)
    at success (https://deno.land/x/postgresjs@v3.3.4/polyfills.js:103:11)
    at eventLoopTick (ext:core/01_core.js:166:11)
    at cachedError (https://deno.land/x/postgresjs@v3.3.4/src/query.js:171:23)
    at new Query (https://deno.land/x/postgresjs@v3.3.4/src/query.js:36:24)
    at sql (https://deno.land/x/postgresjs@v3.3.4/src/index.js:112:11)
    at readData (...)
```

### Steps to reproduce

I was not able to reproduce locally. I think this may be a bug in Deno Deploy.

### Expected behavior

The same code was running fine a few days ago.

**Comment by bartlomieju** [comment]
CC @lucacasonato I believe this is because of the change that causes disabled ops to be removed completely. You might want to add a stub op for that.

**Comment by evelant** [comment]
This is causing a total outage of my app (and I assume anyone else who uses postgresjs). 

This appears to be a major breaking change applied silently. My code just suddenly started crashing without any changes due to this.

See issue in Supabase repo https://github.com/supabase/edge-runtime/issues/81

 Anybody else that can be pinged to get this prioritized? @bartlomieju  @lucacasonato

**Comment by evelant** [comment]
Looks like it's finally back up. I hope the Deno team will analyze how this happened and put steps in place to guard against it. A ~17 hour total outage was not a fun experience.

**Comment by piscisaureus** [comment]
We aim to retain backwards compatibility in Deno Deploy at all times, but unfortunately this change slipped through the cracks. 

Our sincere apologies for the disruption.
