### ISSUE TITLE
[Bug]: ConnectionRefused - Connection refused (os error 111)

### ISSUE THREAD

**Issue by HectorBlisS** [denoland/deploy_feedback#391]
### Problem description

I'm running this code locally with no issues:

```jsx
import { ConnectConfigWithAuthentication } from "https://raw.githubusercontent.com/manyuanrong/deno-smtp/master/config.ts";
import { SmtpClient } from "https://deno.land/x/smtp/mod.ts";
import { load } from "https://deno.land/std/dotenv/mod.ts";

const sendMail = async (email: string) => {
  const client = new SmtpClient();
  const env = await load();
  const config: ConnectConfigWithAuthentication = {
    hostname: "smtp.gmail.com",
    port: 465,
    username: env["EMAIL_USER"],
    password: env["EMAIL_PASS"],
  };
  await client.connectTLS(config);
  await client.send({
    from: "my@mai.com", 
    to: email, 
    subject: "Message",
    content: "Hello",
  });
  await client.close();
};
```

But on production (deno deploy) I got this error:

```bash
at async Object.connectTls (ext:deno_net/02_tls.js:36:51)
    at async SmtpClient.connectTLS (https://deno.land/x/smtp@v0.7.0/smtp.ts:64:18)
    at async sendMail (file:///src/deno.ts:23:3)
    at async file:///src/deno.ts:47:3
    at async dispatch (https://deno.land/x/oak@v12.4.0/middleware.ts:80:7)
    at async dispatch (https://deno.land/x/oak@v12.4.0/middleware.ts:80:7)
    at async dispatch (https://deno.land/x/oak@v12.4.0/middleware.ts:80:7)
    at async Application.#handleRequest (https://deno.land/x/oak@v12.4.0/application.ts:470:9)
2023-05-20 05:57:37
gcp-us-south1
response: { status: 404, type: undefined, hasBody: false, writable: true }
2023-05-20 05:57:37
gcp-us-south1

request: { url: "https://my-project.deno.dev/", method: "POST", hasBody: true }
2023-05-20 05:57:37
gcp-us-south1
[uncaught application error]: ConnectionRefused - Connection refused (os error 111)
```
I'm new to Deno, and I am not sure If I need to grant access for smtp specifically.

I also checked ` await Deno.permissions.query({name:"net"}) ` and is granted.

Any help would be very appreciated 🙏🏽

### Steps to reproduce

1. Use SmtpClient and try to connect
2. It works locally but not in prod (deno deploy)

### Expected behavior

to not refuse connection nor getting error 111

### Environment

deno 1.33.4 (release, x86_64-apple-darwin)
v8 11.4.183.2
typescript 5.0.4

**Comment by satyarohith** [comment]
Hi @HectorBlisS. We don't support outgoing traffic to SMTP ports to prevent abuse. Can you use any service that offers REST API to send emails? 

Thanks for understanding!
