### ISSUE TITLE
Database error in deno deploy

### ISSUE THREAD

**Issue by mrtornado** [denoland/deploy_feedback#430]
I'm getting this error:
``` 
gcp-europe-west3

An error occurred during route handling or page rendering.
TypeError: db.selectFrom(...).select(...).where(...).orWhere is not a function
    at POST (file:///src/routes/api/members/sign-in.ts:50:8)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async handler (file:///src/routes/api/_middleware.ts:20:16)
    at async Server.handler (https://deno.land/x/fresh@1.2.0/src/server/context.ts:388:14)
    at async Server.#respond (https://deno.land/std@0.190.0/http/server.ts:299:18)
```
    
the problem is with .orWhere part. It's working on localhost, also it's working in Deno Deploy before I updated Deno and Fresh. 
But now suddenly after update I get the error. I still have it working in production, but in staging doesn't work. No idea what change that it doesn't work anymore. 
If I remove the .orWhere part is working. 
so the part that brakes it is: `.orWhere("email_address", "=", email)`
Can anybody help ? 

Here is the full sign-in file: 
```javascript
import { Handlers } from "$fresh/server.ts";
import db from "@/db/db.ts";
import { verifyPassword } from "@/utils/hashing.ts";

async function isPasswordValid(
  inputPassword: string,
  storedPassword: string | undefined
): Promise<boolean> {
  if (!storedPassword) {
    return false;
  }

  const isHashed = storedPassword.length === 64;

  if (isHashed) {
    return await verifyPassword(storedPassword, inputPassword, 100000, 32);
  } else {
    return inputPassword.trim() === storedPassword.trim();
  }
}

export const handler: Handlers = {
  async POST(req) {
    let email, password;

    // Check if the request has JSON content
    if (req.headers.get("Content-Type")?.includes("application/json")) {
      const { email: jsonEmail, password: jsonPassword } = await req.json();
      email = jsonEmail;
      password = jsonPassword;
    } else {
      // Fallback to form data
      const form = await req.formData();
      email = String(form.get("email"));
      password = String(form.get("password"));
    }

    const pulledMember = await db
      .selectFrom("member")
      .select([
        "member_key",
        "username",
        "email_address",
        "password",
        "api_key",
        "activated",
        "trial",
      ])
      .where("username", "=", email)
      .orWhere("email_address", "=", email)
      .executeTakeFirst();

    const storedCombined = pulledMember?.password;

    const isValidPassword = storedCombined
      ? await isPasswordValid(password, storedCombined)
      : false;

    if (
      (email === pulledMember?.email_address && isValidPassword) ||
      (email === pulledMember?.username && isValidPassword)
    ) {
      const memberKey = pulledMember?.member_key;
      const username = pulledMember?.username;
      const apiKey = pulledMember?.api_key;
      const activated = pulledMember?.activated;
      const trial = pulledMember?.trial;

      return new Response(
        JSON.stringify({ memberKey, username, apiKey, activated, trial }),
        {
          headers: {
            "Content-Type": "application/json",
          },
        }
      );
    } else {
      return new Response(
        JSON.stringify({ error: "Invalid username or password" }),
        {
          headers: {
            "Content-Type": "application/json",
          },
        }
      );
    }
  },
};
```

**Comment by lucab** [comment]
Thanks for the report.
This doesn't look like a Deno Deploy bug specifically, but it's hard to say what's going on without the whole context.

If you are seeing some differences in behaviors between prod / staging / local-deno, then my guess would be some dependency (possibly a transitive one) not being fully pinned and thus ending up at different versions.

I'd recommend double-checking your tree of dependencies, looking for any unversioned ones. The [Dependency Inspector](https://deno.land/manual@v1.35.0/tools/dependency_inspector) may help you.

**Comment by mrtornado** [comment]
thanks for answering @lucab I'll give it a shot, anyway I changed the code for now and I'll make 2 separate requests to the database so it will work, but pretty odd behavior.
