### ISSUE TITLE
are deno file APIs supported?

### ISSUE THREAD

**Issue by uriva** [denoland/deploy_feedback#472]
### What problem are you trying to solve?

I tried using

```
Deno.makeTempDir
```

and got this:
```
NotSupported: The operation is not supported
    at Object.makeTempDir (ext:deno_fs/30_fs.js:108:15)
    at cloneToLocalDir (file:///src/src/server.ts:22:34)
    at onWebHook (file:///src/src/server.ts:69:25)
    at serveHttp (file:///src/src/server.ts:125:9)
    at eventLoopTick (ext:core/01_core.js:183:11)
```

btw I also need these:

```
Deno.remove
Deno.open
```

### Describe the solution you'd like

deno deploy should work the same as local

### Describe alternatives you've considered

is fs working?

**Comment by ry** [comment]
No, there is no write access to the file system.

**Comment by uriva** [comment]
Why close?
Isn't that a basic functionality needed in many servers?

Also why not make it clear in the docs which APIs are not supported?

**Comment by lucacasonato** [comment]
There is a list here: https://deno.com/deploy/docs/runtime-fs

What do you need a writable FS for?

**Comment by uriva** [comment]
thanks for the link - didn't see it... I would argue it should be in a prominent location, like the `npm:` it can really change one's decision in deciding what to target.

here's what i need it for:


```ts
import { decompress } from "https://deno.land/x/zip@v1.2.5/mod.ts";

const cloneToLocalDir = async ({
  token,
  owner,
  repo,
}: PullRequest): Promise<string> => {
  const downloadDir = await Deno.makeTempDir();
  const res = await fetch(
    `https://github.com/${owner}/${repo}/archive/main.zip`,
    {
      headers: {
        "X-GitHub-Api-Version": "2022-11-28",
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github.v3.raw",
      },
    },
  );
  if (!res.body) throw new Error("empty response");
  const zipFilePath = path.join(downloadDir, "main.zip");
  const file = await Deno.open(zipFilePath, { create: true, write: true });
  await res.body.pipeTo(file.writable);
  file.close();
  await decompress(zipFilePath, downloadDir);
  await Deno.remove(zipFilePath);
  console.log("Repository downloaded successfully!");
  return downloadDir;
};
```
