### ISSUE TITLE
[Bug]: Deploy cannot use `with` import assertions for JSON 

### ISSUE THREAD

**Issue by csvn** [denoland/deploy_feedback#510]
### Problem description

Deno Deploy cannot import JSON with `with` instead of `assert`. This is a bit of a footgun, because it may not be noticed with everything working locally.

### Steps to reproduce

1. Create Deno Deploy playground/project with the following content:
   ```ts
   import { serve } from "https://deno.land/std@0.155.0/http/server.ts";

   serve(async (req: Request) => {
       const json = await import("https://raw.githubusercontent.com/denoland/deno/main/.dprint.json", {
           with: { type: "json" }
       });
       return new Response(JSON.stringify(json, undefined, 2))
   });
   ```
2. When running this endpoint there will be a runtime error:
```
TypeError: Expected a "JavaScriptOrWasm" module but loaded a "JSON" module.
    at async Server.<anonymous> (file:///src/main.ts:4:18)
    at async Server.#respond (https://deno.land/std@0.155.0/http/server.ts:298:18) {
  code: "ERR_MODULE_NOT_FOUND"
```

Changing the `with` to `assert` makes the code work, but it's not really obvious why the above fails.

### Expected behavior

Deno Deploy should ideally be able to run the same code as the Deno runtime without errors.

### Environment

- Deno version 1.37.0

**Comment by csvn** [comment]
The only page I've found on the Deploy docs about differences between the Deno runtime and Deploy is [pricing and limits](https://docs.deno.com/deploy/manual/pricing-and-limits), but this one does not feel like it's maintained.

The docs above does not mention:
- [SMTP ports being blocked on Deploy](https://github.com/denoland/deploy_feedback/issues/391)
- `npm:` namespace not working until recently
- And now the issue above

Is there some other place to see which Deno features that work locally that will not work on Deploy? It hurts a bit when Deploy is otherwise great and easy to use, that there are footguns only noticed when deploying to prod.

**Comment by lucacasonato** [comment]
@csvn Support for the `with` keyword was only released a couple days ago in the CLI. Deploy just hasn't caught up yet. It'll start working on Deploy soon

**Comment by csvn** [comment]
Thanks for the info Luca. I realize the new version was released very recently. Is there a good strategy for avoiding features Deno Deploy do not yet support (like comparing Deploy version with Deno client version or something)? If it is lagging behind, there will likely be new TC39 features that the client supports but Deploy does not in the future too.

**Comment by csvn** [comment]
It would be less of an issue if it was possible to have different environment variables on prod vs preview environments somehow (#144). It's harder to test things in prod, but currently it's only there the issue I had above was noticed.

**Comment by csvn** [comment]
Deno Deploy now supports `with` import attributes. We could close this issue, though I still feel like it would be nice with some overview on what works and what doesn't in the runtime vs Deploy, so you don't have to deploy first and test it live.
