### ISSUE TITLE
[Bug]: Deploy to Deno Failed after Upgrading Fresh to 1.6.3

### ISSUE THREAD

**Issue by cj-1010-1414** [denoland/deploy_feedback#597]
### Problem description

```
error: Uncaught (in promise) SyntaxError: The requested module 'js-beautify' does not provide an export named 'html' at file:///home/runner/work/pendaftaran-efr/pendaftaran-efr/node_modules/.deno/resend@3.0.0/node_modules/@react-email/render/dist/index.mjs:49:10
  const manifest = (await import(toFileUrl(join(dir, "fresh.gen.ts")).href))
                    ^
    at async dev (https://deno.land/x/fresh@1.6.3/src/dev/dev_command.ts:38:21)
    at async file:///home/runner/work/pendaftaran-efr/pendaftaran-efr/dev.ts:8:1
Error: Process completed with exit code 1.
```

This is the message. The error seems to happen at npm resend library. But this doesn't happen at version 1.6.1, prior updating.

This also doesn't happen on local development machine with 1.6.3. Only on Deno deploy.

### Steps to reproduce

1. Installing Fresh 1.6.1
2. Import `npm:resend`
3. Use it
4. Upgrade Fresh to 1.6.3

### Expected behavior

It should have worked as there's no problem at local machine.

### Environment

version: Deno 1.39.4
os: Ubuntu 22.04

**Comment by piscisaureus** [comment]
CC @marvinhagemeister

**Comment by cj-1010-1414** [comment]
It's deployed now. But I don't know why

**Comment by marvinhagemeister** [comment]
@piscisaureus I can't find something that would relate to this being an issue with Fresh. The module in question is a cjs module and the module loading portion in Deno should take care of that.
