### ISSUE TITLE
[Bug]: Worker is not defined when using bcrypt genSalt

### ISSUE THREAD

**Issue by charlesetc** [denoland/deploy_feedback#613]
### Problem description

```
ReferenceError: Worker is not defined
    at Module.genSalt (https://deno.land/x/bcrypt@v0.4.1/src/main.ts:48:16)
    at file:///src/src/index.jsx:102:29
    at eventLoopTick (ext:core/01_core.js:182:7)
    at async dispatch (https://deno.land/x/hono@v4.0.0/compose.ts:45:17)
    at async dispatch (https://deno.land/x/hono@v4.0.0/compose.ts:45:17)
    at async file:///src/src/session.js:19:5
    at async dispatch (https://deno.land/x/hono@v4.0.0/compose.ts:45:17)
    at async middleware (https://deno.land/x/hono_sessions@v0.3.4/src/Middleware.ts:101:5)
    at async dispatch (https://deno.land/x/hono@v4.0.0/compose.ts:45:17)
    at async flash (file:///src/src/flash.js:7:3)

2/10/2024, 12:08:12 PM
gcp-us-east4
```

I don't think I'm doing anything fancy - this happens just on deno deploy at `const salt = await bcrypt.genSalt(8);`

Thanks! Let me know if I should forward this somewhere else 😊

### Steps to reproduce

I think calling bcrypt.genSalt on deno deploy is the issue

### Expected behavior

To not raise an error

### Environment

It's happening on deno deploy

**Comment by charlesetc** [comment]
Update: seems to be a problem with `bcrypt.hash` even without the salt...
