### ISSUE TITLE
[Bug]: I can't access the KV playground example anymore

### ISSUE THREAD

**Issue by PabloPomodoro** [denoland/deploy_feedback#614]
### Problem description

After I tried to use a random number generator to increase the visitor count in the playground example and received an error message, I tried restructuring the code and tried deploying it a second time, it displayed an HTTP 500, but it is actually 200 with the error from below and now when I try to open it I get a HTTP 404 and after a reload the 200 displayed as 500 again.

At the moment this doesn't affect the other tutorials or functionality of deno deploy.

### Steps to reproduce
```
{
    "name": "ApiError",
    "status": 404,
    "code": "deploymentNotFound",
    "traceId": "0d5cda3b38a428eba2bc3b4cb66e7582",
    "retryAfterSec": null,
    "message": "The deployment you are requesting was not found, or you do not have access to view it.",
    "stack": "ApiError: The deployment you are requesting was not found, or you do not have access to view it.\n    at y (file:///src/dist/server.js:22:2379)\n    at eventLoopTick (ext:core/01_core.js:182:7)\n    at async get (file:///src/dist/server.js:355:6896)\n    at async fetchRouteData (https://deno.land/x/aleph@1.0.0-alpha.68/server/routing.ts:64:23)\n    at async Server.c (file:///src/dist/server.js:70:19097)\n    at async Server.#respond (https://deno.land/std@0.142.0/http/server.ts:298:18)"
}
```

After reload

```
[
                            {
                                "url": "\/_app",
                                "params": {
                                },
                                "filename": ".\/routes\/_app.tsx",
                                "withData": true,
                                "data": {
                                    "user": {
//userid
                                        "avatarUrl": "https:\/\/avatars.githubusercontent.com\/u\/157257164?v=4",
//githubid
                                        "isBlocked": false,
                                        "isAdmin": false,
                                        "pro": false,
                                        "subscription": {
                                            "plan": "free",
                                            "currentPeriodStart": "2024-01-28T11:59:29Z",
                                            "currentPeriodEnd": "2024-02-28T11:59:29Z"
                                        },
                                        "features": [
                                            "database"
                                        ],
                                        "updatedAt": "2024-02-04T23:48:14.426851Z",
                                        "createdAt": "2024-01-28T11:59:27.369017Z"
                                    },
                                    "organizations": [
                                        {
                                            "id": "efc62b11-2e5c-458d-9a31-c45661b280b5",
                                            "name": null,
                                            "pro": false,
                                            "subscription": {
                                                "plan": "free",
                                                "currentPeriodStart": "2024-01-28T11:59:29Z",
                                                "currentPeriodEnd": "2024-02-28T11:59:29Z"
                                            },
                                            "features": {
                                            },
                                            "createdAt": "2024-01-28T11:59:27.369017Z",
                                            "updatedAt": "2024-01-28T11:59:28.615277Z"
                                        }
                                    ],
                                    "sudo": false
                                }
                            },
                            {
                                "url": "\/tutorial\/tutorial-http-kv",
                                "params": {
                                    "pid": "tutorial-http-kv"
                                },
                                "filename": ".\/routes\/tutorial\/$pid.tsx",
                                "withData": true,
                                "error": {
                                    "message": "The deployment you are requesting was not found, or you do not have access to view it.",
                                    "stack": "ApiError: The deployment you are requesting was not found, or you do not have access to view it.\n    at y (file:\/\/\/src\/dist\/server.js:22:2379)\n    at eventLoopTick (ext:core\/01_core.js:182:7)\n    at async get (file:\/\/\/src\/dist\/server.js:355:6896)\n    at async fetchData (https:\/\/deno.land\/x\/aleph@1.0.0-alpha.68\/server\/renderer.ts:375:17)\n    at async https:\/\/deno.land\/x\/aleph@1.0.0-alpha.68\/server\/renderer.ts:410:23\n    at async Promise.all (index 1)\n    at async initSSR (https:\/\/deno.land\/x\/aleph@1.0.0-alpha.68\/server\/renderer.ts:346:19)\n    at async Object.fetch (https:\/\/deno.land\/x\/aleph@1.0.0-alpha.68\/server\/renderer.ts:75:48)\n    at async Server.#respond (https:\/\/deno.land\/std@0.142.0\/http\/server.ts:298:18)"
                                }
                            }
                        ]</script>
                    <script type="module" nonce="lshtgr43">
                        import $0 from "/routes/_app.tsx?v=rh4e9z4adw44";
                        import $1 from "/routes/tutorial/$pid.tsx?v=rh4e9z4adw44";
                        window.__ROUTE_MODULES = {
                            "./routes/_app.tsx": {
                                defaultExport: $0,
                                withData: true
                            },
                            "./routes/tutorial/$pid.tsx": {
                                defaultExport: $1,
                                withData: true
                            }
                        };
```

### Expected behavior

To be able to edit my tutorial project and remove the random number of visitors functionality.

### Environment

- Deno Playground
- Chrome Version 121.0.6167.161 (Official Build) (64-bit)

### Additional context

Your help is much appreciated!

**Comment by PabloPomodoro** [comment]
Edit: I didn't know this would be submitted as a github issue.

**Comment by PabloPomodoro** [comment]
Update: I now tried modifying the "REST API with Hono" example and the same thing happend there as well.
