### ISSUE TITLE
[Bug]: Internal Server Error

### ISSUE THREAD

**Issue by sarcasterXO** [denoland/deploy_feedback#739]
### Problem description

I am trying to deploy a Next.js v15 project. Once the project is deployed and I try to open the website, it shows me `Internal Server Error` and when I check the Deno Logs it shows:
```
 ▲ Next.js 14.2.16
 - Local:        http://localhost:80
 - Network:      http://0.0.0.0:80
 
 ✓ Starting...
 
 Env vars cannot begin with DENO_
  
NotFound: No such file or directory (os error 2): readfile '/src/.next/server/font-manifest.json'
    at Object.readFileSync (ext:deno_fs/30_fs.js:834:10)
    at readFileSync (ext:deno_node/_fs/_fs_readFile.ts:52:21)
    at loadManifest (file:///node_modules/.deno/next@14.2.16/node_modules/next/dist/server/load-manifest.js:36:52)
    at requireFontManifest (file:///node_modules/.deno/next@14.2.16/node_modules/next/dist/server/require.js:117:57)
    at NextNodeServer.getFontManifest (file:///node_modules/.deno/next@14.2.16/node_modules/next/dist/server/next-server.js:741:49)
    at new Server (file:///node_modules/.deno/next@14.2.16/node_modules/next/dist/server/base-server.js:353:72)
    at new NextNodeServer (file:///node_modules/.deno/next@14.2.16/node_modules/next/dist/server/next-server.js:146:9)
    at NextServer.createServer (file:///node_modules/.deno/next@14.2.16/node_modules/next/dist/server/next.js:175:24)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async file:///node_modules/.deno/next@14.2.16/node_modules/next/dist/server/next.js:213:31 {
  name: "NotFound",
  code: "ENOENT"
}

Failed to handle request for /favicon.ico

PermissionDenied: 'Deno.exit' is not allowed in this context.
    at Object.exit (ext:deno_deploy/os.js:69:9)
    at Process.reallyExit (node:process:314:15)
    at Process.exit (node:process:63:11)
    at ServerImpl.<anonymous> (file:///node_modules/.deno/next@14.2.16/node_modules/next/dist/server/lib/start-server.js:276:25)
    at eventLoopTick (ext:core/01_core.js:175:7) {
  name: "PermissionDenied"
}
```

### Steps to reproduce

- Step 1: Create a Next.js v15 project.
- Step 2: Use `bun` as a package manager instead of deno
- Step 3: Push your project on GitHub
- Step 4: Go on Deno Deploy and deploy your project using GitHub repository
- Step 5: Visit the deployed website.

### Expected behavior

The website should load properly without any errors. 

### Environment

- Bun Verson: `1.1.29`
- Next.js Version: `15.0.1`

**Note: I am using `npm` for installing and building in Deno Deploy**

**Comment by wesbos** [comment]
Next.js published an example of using Deno Deploy here: https://github.com/nextjs/deploy-deno 

You likely just need to tweak your build + deploy commands
