### ISSUE TITLE
Java can't establish SSL connection to Deno Deploy servers

### ISSUE THREAD

**Issue by aglitchman** [denoland/deploy_feedback#87]
**The issue description:**
Looks like, Java applications can't establish SSL connections to Deno Deploy servers. This has been happening since yesterday.

By the way, my Java app does a regular HTTPS GET request to my app on Deno Deploy, nothing special.

**To reproduce:**
1. `git clone https://github.com/dimalinux/SSLPing.git`
2. Run `java -jar SSLPing/dist/SSLPing.jar helloworld.letsencrypt.org 443` to test that it works. It should return
```
About to connect to 'helloworld.letsencrypt.org' on port 443
Successfully connected
```
3. Run `java -jar SSLPing/dist/SSLPing.jar https-test.deno.dev 443` to get:
```
About to connect to 'https-test.deno.dev' on port 443
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1598)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1426)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1324)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
        at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:829)
        at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1199)
        at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1171)
        at to.noc.sslping.SSLPing.main(SSLPing.java:41)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:483)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1418)
        ... 6 more
```

Actually, https://https-test.deno.dev/ is the hello application from [examples](https://dash.deno.com/examples/hello.js).

**Tested Java versions:**
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
```

```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)
```

**Comment by lucacasonato** [comment]
Thanks for the report. I have opened an internal issue to get this sorted ASAP.

**Comment by bnoordhuis** [comment]
We pushed a fix just now that addresses that. Thanks for the report!

**Comment by bnoordhuis** [comment]
For posterity, https://github.com/denoland/deno_install/issues/191 turned out to be the same issue, but with powershell and certain versions of curl.exe.
